config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'home#index'
  get 'home/create'
  get 'requested_jobs/create_job'
  resources :company_details
  resources :job_posts
  resources :requested_jobs
  resources :experiences
  resources :education_qualifications
  resources :members
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/company_detail.rb
class CompanyDetail < ApplicationRecord
  #belongs_to :member
  has_many :job_post
end

app/controllers/company_details_controller.rb
class CompanyDetailsController < ApplicationController
  before_action :set_company_detail, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!
  # GET /company_details
  # GET /company_details.json

  def index
    if Member.find_by_user_id(current_user.id) != nil
      me=Member.find_by_user_id(current_user.id)
      @company_details = CompanyDetail.where(:member_id=>me.id)
      @requested_job = RequestedJobs.where(:company_id => @company_details.id , :emp_id=> me.id)
    else
      redirect_to "/members/new"
    end
  end

  # GET /company_details/1
  # GET /company_details/1.json
  def show
  end

  # GET /company_details/new
  def new
    if Member.find_by_user_id(current_user.id) != nil
      me=Member.find_by_user_id(current_user.id)
      @company_detail = CompanyDetail.new
    else
      redirect_to "/members/new"
    end
  end

  # GET /company_details/1/edit
  def edit
  end

  # POST /company_details
  # POST /company_details.json
  def create
    @company_detail = CompanyDetail.new(company_detail_params)

    respond_to do |format|
      if @company_detail.save
        @company_detail.update_attributes(:member_id=> params[:company_detail][:member_id])
        format.html { redirect_to '/company_details', notice: 'Company detail was successfully created.' }
      else
        format.html { render :new }
        format.json { render json: @company_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /company_details/1
  # PATCH/PUT /company_details/1.json
  def update
    respond_to do |format|
      if @company_detail.update(company_detail_params)
        format.html { redirect_to '/company_details', notice: 'Company detail was successfully updated.' }
      else
        format.html { render :edit }
        format.json { render json: @company_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /company_details/1
  # DELETE /company_details/1.json
  def destroy
    @company_detail.destroy
    respond_to do |format|
      format.html { redirect_to company_details_url, notice: 'Company detail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company_detail
      @company_detail = CompanyDetail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_detail_params
      params.require(:company_detail).permit(:name, :address, :keyword, :description, :url)
    end
end

app/helpers/company_details_helper.rb
module CompanyDetailsHelper
end

app/views/company_details/_form.html.erb
<%= form_for(company_detail) do |f| %>
  <% if company_detail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(company_detail.errors.count, "error") %> prohibited this company_detail from being saved:</h2>

      <ul>
      <% company_detail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :address %>
    <%= f.text_area :address %>
  </div>

  <div class="field">
    <%= f.label :keyword %>
    <%= f.text_field :keyword %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :url %>
    <%= f.text_field :url %>
    <div class="field">
      <%tmp=Member.find_by_user_id(current_user.id)%>
      <%= f.hidden_field :member_id,:value=> tmp.id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/company_details/edit.html.erb
<h1>Editing Company Detail</h1>

<%= render 'form', company_detail: @company_detail %>

<%= link_to 'Show', @company_detail %> |
<%= link_to 'Back', '/company_details' %>

app/views/company_details/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Company Details</h1>
<h6>Click 'Show' to see jobs you have posted!</h6>
<%= link_to 'New Company Detail', new_company_detail_path %>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Keyword</th>
      <th>Description</th>
      <th>Url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @company_details.each do |company_detail| %>
      <tr>
        <td><%= company_detail.name %></td>
        <td><%= company_detail.address %></td>
        <td><%= company_detail.keyword %></td>
        <td><%= company_detail.description %></td>
        <td><%= company_detail.url %></td>
        <td><%= link_to 'Show', company_detail %></td>
        <td><%= link_to 'Edit', edit_company_detail_path(company_detail) %></td>
        <td><%= link_to 'Destroy', company_detail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/company_details/new.html.erb
<h1>New Company Detail</h1>

<%= render 'form', company_detail: @company_detail %>

<%= link_to 'Back', '/company_details' %>

app/views/company_details/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @company_detail.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @company_detail.address %>
</p>

<p>
  <strong>Keyword:</strong>
  <%= @company_detail.keyword %>
</p>

<p>
  <strong>Description:</strong>
  <%= @company_detail.description %>
</p>

<p>
  <strong>Url:</strong>
  <%= @company_detail.url %>
</p>

<%= link_to 'Edit', edit_company_detail_path(@company_detail) %> |
<%= link_to 'Back', '/company_details' %>

<%@job_posts = JobPost.where(:company_id=>@company_detail.id)%>
<%p @job_posts%>
<%p "=========================================="%>
<h1>Job Posts</h1>
<%= link_to 'New Job Post', new_job_post_path %>
<table>
  <thead>
    <tr>
      <th>Company</th>
      <th>Required on</th>
      <th>Etc</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @job_posts.each do |job_post| %>
      <tr>
        <% tmp = CompanyDetail.find(job_post.company_id) %>
        <td><%= tmp.name %></td>
        <td><%= job_post.required_on %></td>
        <td><%= job_post.etc %></td>
        <td><%= job_post.description %></td>
        <td><%= link_to 'Show', job_post %></td>
        <td><%= link_to 'Edit', edit_job_post_path(job_post) %></td>
        <td><%= link_to 'Destroy', job_post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%end%>
      </tr>
  </tbody>
</table>