config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'home#index'
  get 'home/create'
  get 'requested_jobs/create_job'
  resources :company_details
  resources :job_posts
  resources :requested_jobs
  resources :experiences
  resources :education_qualifications
  resources :members
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/education_qualification.rb
class EducationQualification < ApplicationRecord
  # belongs_to :member
end

app/controllers/education_qualifications_controller.rb
class EducationQualificationsController < ApplicationController
  before_action :set_education_qualification, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!
  # GET /education_qualifications
  # GET /education_qualifications.json
  def index
    if Member.find_by_user_id(current_user.id) != nil
      me=Member.find_by_user_id(current_user.id)
      @education_qualifications = EducationQualification.where(:member_id=>me.id)
    end
  end

  # GET /education_qualifications/1
  # GET /education_qualifications/1.json
  def show
  end

  # GET /education_qualifications/new
  def new
    @education_qualification = EducationQualification.new
  end

  # GET /education_qualifications/1/edit
  def edit
  end

  # POST /education_qualifications
  # POST /education_qualifications.json
  def create
    @education_qualification = EducationQualification.new(education_qualification_params)

    respond_to do |format|
      if @education_qualification.save
        @education_qualification.update_attributes(:member_id=> params[:education_qualification][:member_id])
        format.html { redirect_to '/members', notice: 'Education qualification was successfully created.' }
      else
        format.html { render :new }
        format.json { render json: @education_qualification.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /education_qualifications/1
  # PATCH/PUT /education_qualifications/1.json
  def update
    respond_to do |format|
      if @education_qualification.update(education_qualification_params)
        @education_qualification.update_attributes(:member_id=> params[:education_qualification][:member_id])
        format.html { redirect_to '/members', notice: 'Education qualification was successfully updated.' }
      else
        format.html { render :edit }
        format.json { render json: @education_qualification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /education_qualifications/1
  # DELETE /education_qualifications/1.json
  def destroy
    @education_qualification.destroy
    respond_to do |format|
      format.html { redirect_to education_qualifications_url, notice: 'Education qualification was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_education_qualification
      @education_qualification = EducationQualification.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def education_qualification_params
      params.require(:education_qualification).permit(:user_id, :intitution_name, :passed_out, :percentage)
    end
end

app/helpers/education_qualifications_helper.rb
module EducationQualificationsHelper
end

app/views/education_qualifications/_form.html.erb
<%= form_for(education_qualification) do |f| %>
  <% if education_qualification.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(education_qualification.errors.count, "error") %> prohibited this education_qualification from being saved:</h2>

      <ul>
      <% education_qualification.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%member=Member.find_by_user_id(current_user.id)%>
    <% f.label :member_id %>
    <%= f.hidden_field :member_id,:value=> member.id %>
  </div>

  <div class="field">
    <%= f.label :intitution_name %>
    <%= f.text_field :intitution_name %>
  </div>

  <div class="field">
    <%= f.label :passed_out %>
    <%= f.text_field :passed_out %>
  </div>

  <div class="field">
    <%= f.label :percentage %>
    <%= f.number_field :percentage %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/education_qualifications/edit.html.erb
<h1>Editing Education Qualification</h1>

<%= render 'form', education_qualification: @education_qualification %>

<%= link_to 'Show', @education_qualification %> |
<%= link_to 'Back', education_qualifications_path %>

app/views/education_qualifications/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Education Qualifications</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Intitution name</th>
      <th>Passed out</th>
      <th>Percentage</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @education_qualifications.each do |education_qualification| %>
      <tr>
        <td><%= education_qualification.member_id %></td>
        <td><%= education_qualification.intitution_name %></td>
        <td><%= education_qualification.passed_out %></td>
        <td><%= education_qualification.percentage %></td>
        <td><%= link_to 'Show', education_qualification %></td>
        <td><%= link_to 'Edit', edit_education_qualification_path(education_qualification) %></td>
        <td><%= link_to 'Destroy', education_qualification, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Education Qualification', new_education_qualification_path %>

app/views/education_qualifications/new.html.erb
<h1>New Education Qualification</h1>

<%= render 'form', education_qualification: @education_qualification %>

<%= link_to 'Back', education_qualifications_path %>

app/views/education_qualifications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @education_qualification.member_id %>
</p>

<p>
  <strong>Intitution name:</strong>
  <%= @education_qualification.intitution_name %>
</p>

<p>
  <strong>Passed out:</strong>
  <%= @education_qualification.passed_out %>
</p>

<p>
  <strong>Percentage:</strong>
  <%= @education_qualification.percentage %>
</p>

<%= link_to 'Edit', edit_education_qualification_path(@education_qualification) %> |
<%= link_to 'Back', education_qualifications_path %>