config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'home#index'
  get 'home/create'
  get 'requested_jobs/create_job'
  resources :company_details
  resources :job_posts
  resources :requested_jobs
  resources :experiences
  resources :education_qualifications
  resources :members
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/member.rb
class Member < ApplicationRecord
  # validates_processing_of :photo
  validate :image_size_validation

  mount_uploader :resume, AttachmentUploader # Tells rails to use this uploader for this model.
  validates :name, presence: true # Make sure the owner's name is present.


  has_one :user
  has_many :education_qualification
  has_many :company_detail
  has_many :requested_job
  has_many :experience
  mount_uploader :photo, ImageUploader


  private

  def image_size_validation
    errors[:photo] << "should be less than 500KB" if photo.size > 0.5.megabytes
  end

end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!
  # GET /members
  # GET /members.json
  def index
    if Member.find_by_user_id(current_user.id) != nil
      me=Member.find_by_user_id(current_user.id)
      @members = Member.all
      @education_qualifications = EducationQualification.where(:member_id=>me.id)
      @experiences = Experience.where(:member_id=>me.id)
    else
      redirect_to "/members/new"
    end
  end

  # GET /members/1
  # GET /members/1.json
  def show
  end

  # GET /members/new
  def new
    tmp=Member.find_by_user_id(current_user.id)
    if tmp != nil
      flash[:notice]="You already have a account"
      redirect_to "/members"
    else
      @member = Member.new
    end
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members
  # POST /members.json
  def create
    @member = Member.new(member_params)
    respond_to do |format|
      if @member.save
        @member.update_attributes(:user_id => current_user.id)
        format.html { redirect_to '/members', notice: 'Member was successfully created.' }
      else
        format.html { render :new }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1
  # PATCH/PUT /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to '/members', notice: 'Member was successfully updated.' }
      else
        format.html { render :edit }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member.destroy
    respond_to do |format|
      format.html { redirect_to members_url, notice: 'Member was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def member_params
      params.require(:member).permit(:name, :address1, :address2, :phone, :email, :photo, :role, :resume, :locations, :links, :description, :father_name)
    end
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/_form.html.erb
<%= form_for(member) do |f| %>
  <% if member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
      <% member.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :address1 %>
    <%= f.text_field :address1 %>
  </div>

  <div class="field">
    <%= f.label :address2 %>
    <%= f.text_field :address2 %>
  </div>

  <div class="field">
    <%= f.label :phone %>
    <%= f.text_field :phone %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :photo %>
    <%= f.file_field :photo %>
    <% if f.object.photo? %>
      <%= image_tag f.object.photo.thumb.url %>
      <%= f.label :remove_photo %>
      <%= f.check_box :remove_photo %>
    <% end %>
  </div>

  <div class="field">
    <%= f.label :role %>
    <%= f.text_field :role %>

  </div>

  <div class="field">
    <%= f.label :resume %>
    <%= f.file_field :resume%>
    <% if f.object.photo? %>
        <%= f.object.resume.url%>
    <%end%>
  </div>

  <div class="field">
    <%= f.label :locations %>
    <%= f.text_field :locations %>
  </div>

  <div class="field">
    <%= f.label :links %>
    <%= f.text_field :links %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :father_name %>
    <%= f.text_field :father_name %>
  </div>
  <div class="field">
    <%= f.label "Has Company" %>
    <%= f.check_box :father_name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/members/edit.html.erb
<h1>Editing Member</h1>

<%= render 'form', member: @member %>

<%= link_to 'Show', @member %> |
<%= link_to 'Back', members_path %>

app/views/members/index.html.erb
<p id="notice"><%= notice %></p>
<div class="nav-bar">
<%= link_to 'Manage Password',edit_user_registration_path, :class => 'navbar-link-pass' %>
</div>
<% @members.each do |member| %>
    <div  class="avatar">
      <%= image_tag(member.photo.url.to_s) %>
    </div>
      <p>Name: <%= member.name %></p>
      <p>Address1:  <%= member.address1 %></p>
      <p>Address2:  <%= member.address2 %></p>
      <p>Phone  <%= member.phone %></p>
      <p>Email:     <%= member.email %></p>
      <p>Role:  <%= member.role %></td></p>
      <p>Resume : <%= link_to "click here", member.resume_url %></p>
      <p>Location: <%= member.locations %></p>
      <p>Link: <%= member.links %></p>
      <p>Description: <%= member.description %></p>
      <p>Father Name<%= member.father_name %></p>
        <%= link_to "<button>Edit</button>".html_safe, edit_member_path(member) %></td>
        <%= link_to "<button>Destroy</button>".html_safe, member, method: :delete, data: { confirm: 'Are you sure?' } %></td>

    <% end %>

<%= link_to 'Add Education Qualification', "education_qualifications/new" %>
<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Intitution name</th>
      <th>Passed out</th>
      <th>Percentage</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @education_qualifications.each do |education_qualification| %>
      <tr>
        <td><%= education_qualification.member_id %></td>
        <td><%= education_qualification.intitution_name %></td>
        <td><%= education_qualification.passed_out %></td>
        <td><%= education_qualification.percentage %></td>
        <td><%= link_to "<button>Show</button>".html_safe, education_qualification %></td>
        <td><%= link_to "<button>Edit</button>".html_safe, edit_education_qualification_path(education_qualification) %></td>
        <td><%= link_to "<button>Destroy</button>".html_safe, education_qualification, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Add Experice', "experiences/new" %>
<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Company name</th>
      <th>Worked as</th>
      <th>Description</th>
      <th>Experience</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @experiences.each do |experience| %>
      <tr>
        <td><%= experience.member_id %></td>
        <td><%= experience.company_name %></td>
        <td><%= experience.worked_as %></td>
        <td><%= experience.description %></td>
        <td><%= experience.experience %></td>
        <td><%= link_to "<button>Show</button>".html_safe, experience %></td>
        <td><%= link_to "<button>Edit</button>".html_safe, edit_experience_path(experience) %></td>
        <td><%= link_to "<button>Destroy</button>".html_safe, experience, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/members/new.html.erb
<h1>New Member</h1>

<%= render 'form', member: @member %>

<%= link_to 'Back', members_path %>

app/views/members/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @member.name %>
</p>

<p>
  <strong>Address1:</strong>
  <%= @member.address1 %>
</p>

<p>
  <strong>Address2:</strong>
  <%= @member.address2 %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @member.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @member.email %>
</p>

<p>
  <strong>Photo:</strong>
  <%= @member.photo %>
</p>

<p>
  <strong>Role:</strong>
  <%= @member.role %>
</p>

<p>
  <strong>Resume:</strong>
  <%= @member.resume %>
</p>

<p>
  <strong>Locations:</strong>
  <%= @member.locations %>
</p>

<p>
  <strong>Links:</strong>
  <%= @member.links %>
</p>

<p>
  <strong>Description:</strong>
  <%= @member.description %>
</p>

<p>
  <strong>Father name:</strong>
  <%= @member.father_name %>
</p>

<%= link_to 'Edit', edit_member_path(@member) %> |
<%= link_to 'Back', '/members/index' %>